export type Suit = 'H' | 'D' | 'C' | 'S';
export type Rank = '2' | '3' | '4' | '5' | '6' | '7' | '8' | '9' | '10' | 'J' | 'Q' | 'K' | 'A';

export interface Card {
  suit: Suit;
  rank: Rank;
  id: string;
}

export interface BoardCell {
  card: Card | null; // null for corners
  chip: string | null; // player color, or 'wild' for corners
  isLocked: boolean;
}

export type GameStatus = 'waiting' | 'playing' | 'finished';

export interface LastMove {
  playerId: string;
  row: number;
  col: number;
  type: 'place' | 'remove';
}

/**
 * Server-side, authoritative player record.
 * `playerId` is a persistent identity generated by the client and stored in
 * localStorage, so a player keeps their seat and hand across page refreshes
 * or brief disconnects. `socketId` is the *current* live connection and can
 * be null while the player is disconnected but still seated.
 */
export interface Player {
  playerId: string;
  socketId: string | null;
  name: string;
  color: string;
  hand: Card[];
  connected: boolean;
  surrendered?: boolean;
}

export type Coord = [number, number];

export interface GameStats {
  startTime: number;
  endTime: number;
  durationSeconds: number;
  totalMoves: number;
  sequencesCount: number;
}

export interface RewardBreakdown {
  matchComplete: number;
  victory: number;
  sequences: number;
  streakBonus: number;
  totalEarned: number;
}

export interface MatchHistoryRecord {
  matchId: string;
  timestamp: number;
  roomCode: string;
  mode: string;
  isTeam: boolean;
  winningTeam?: string | null;
  winnerName: string;
  isWin: boolean;
  sequencesCount: number;
  durationSeconds: number;
  coinsEarned: number;
}

export interface PlayerAchievement {
  achievementId: string;
  unlocked: boolean;
  unlockedAt: number | null;
  claimed: boolean;
}

export interface PlayerProfile {
  playerId: string;
  name: string;
  coins: number;
  totalGames: number;
  wins: number;
  losses: number;
  currentWinStreak: number;
  bestWinStreak: number;
  totalSequences: number;
  lastDailyClaim?: number; // epoch ms
  dailyStreak?: number; // 0..7
  matchHistory: MatchHistoryRecord[];
  achievements: Record<string, PlayerAchievement>;
}

/** Undo snapshot stored on server to reverse moves */
export interface UndoSnapshot {
  board: BoardCell[][];
  players: Player[];
  turnIndex: number;
  deck: Card[];
  lastMove: LastMove | null;
  winner: string | null;
  status: GameStatus;
  gameStats: GameStats | null;
}

/** Server-side, authoritative game state. Never sent to clients as-is. */
export interface GameState {
  roomId: string;
  board: BoardCell[][];
  players: Player[];
  turnIndex: number;
  deck: Card[];
  status: GameStatus;
  winner: string | null;
  lastMove: LastMove | null;
  winningSequences?: Coord[][];
  winningCells?: Coord[];
  isTeamGame?: boolean;
  winningTeam?: string | null;
  winningPlayerNames?: string[];
  gameStats?: GameStats | null;
  startTime?: number;
  totalMoves?: number;
  rematchVotes?: string[];
  startingTurnIndex?: number;
  turnDeadline?: number | null;
  turnDurationSeconds?: number;
  undoAvailableForPlayerId?: string | null;
  undoDeadline?: number | null;
  undoSnapshot?: UndoSnapshot | null;
  rewardBreakdowns?: Record<string, RewardBreakdown>;
}

/**
 * Redacted, per-recipient view of a player. Only the requesting player's own
 * `hand` is populated; everyone else's is an empty array plus a `handCount`
 * so the UI can render card-backs / counts without leaking hidden information.
 */
export interface ClientPlayer {
  playerId: string;
  name: string;
  color: string;
  handCount: number;
  hand: Card[];
  connected: boolean;
  surrendered?: boolean;
}

/** Redacted, per-recipient view of the game. This is what actually goes over the wire. */
export interface ClientGameState {
  roomId: string;
  board: BoardCell[][];
  players: ClientPlayer[];
  turnIndex: number;
  deckCount: number;
  status: GameStatus;
  winner: string | null;
  lastMove: LastMove | null;
  youPlayerId: string;
  winningSequences?: Coord[][];
  winningCells?: Coord[];
  isTeamGame?: boolean;
  winningTeam?: string | null;
  winningPlayerNames?: string[];
  gameStats?: GameStats | null;
  rematchVotes?: string[];
  turnDeadline?: number | null;
  turnDurationSeconds?: number;
  undoAvailableForPlayerId?: string | null;
  undoDeadline?: number | null;
  rewardBreakdown?: RewardBreakdown | null;
}

export const PLAYER_COLORS = ['#2563eb', '#dc2626', '#16a34a', '#ca8a04'] as const;
export const COLOR_NAMES: Record<string, string> = {
  '#2563eb': 'Blue',
  '#dc2626': 'Red',
  '#16a34a': 'Green',
  '#ca8a04': 'Gold',
};

export const BOARD_LAYOUT: (string | null)[][] = [
  [null, '2S', '3S', '4S', '5S', '6S', '7S', '8S', '9S', null],
  ['6C', '5C', '4C', '3C', '2C', 'AH', 'KH', 'QH', '10H', '10S'],
  ['7C', 'AS', '2D', '3D', '4D', '5D', '6D', '7D', '9H', 'QS'],
  ['8C', 'KS', '6C', '5C', '4C', '3C', '2C', '8D', '8H', 'KS'],
  ['9C', 'QS', '7C', '6H', '5H', '4H', 'AH', '9D', '7H', 'AS'],
  ['10C', '10S', '8C', '7H', '2H', '3H', 'KH', '10D', '6H', '2D'],
  ['QC', '9S', '9C', '8H', '9H', '10H', 'QH', 'QD', '5H', '3D'],
  ['KC', '8S', '10C', 'QC', 'KC', 'AC', 'AD', 'KD', '4H', '4D'],
  ['AC', '7S', '6S', '5S', '4S', '3S', '2S', '2H', '3H', '5D'],
  [null, 'AD', 'KD', 'QD', '10D', '9D', '8D', '7D', '6D', null]
];

export function parseCardString(s: string | null): Card | null {
  if (!s) return null;
  const rank = s.slice(0, -1) as Rank;
  const suit = s.slice(-1) as Suit;
  return { rank, suit, id: s };
}

export function createDeck(): Card[] {
  const suits: Suit[] = ['H', 'D', 'C', 'S'];
  const ranks: Rank[] = ['2', '3', '4', '5', '6', '7', '8', '9', '10', 'J', 'Q', 'K', 'A'];
  const deck: Card[] = [];

  // Sequence's board has each card printed twice, so a standard digital
  // implementation deals from two merged decks (104 cards) regardless of
  // player count.
  for (let i = 0; i < 2; i++) {
    for (const suit of suits) {
      for (const rank of ranks) {
        deck.push({ suit, rank, id: `${rank}${suit}-${i}` });
      }
    }
  }
  return shuffle(deck);
}

function shuffle<T>(array: T[]): T[] {
  const newArray = [...array];
  for (let i = newArray.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [newArray[i], newArray[j]] = [newArray[j], newArray[i]];
  }
  return newArray;
}
